### ISSUE TITLE
Receiving errors when trying to create a frame processors plugin on iOS and Android

### ISSUE THREAD

**Issue by Egbert-Jan** [mrousavy/vision-camera-image-labeler#21]
Hello, 

I have followed the guides for creating frame-processors for both iOS and Android: https://www.react-native-vision-camera.com/docs/guides/frame-processors-plugins-overview.

When trying to build it fails on both platforms and I don't know how to fix it. 
I started with a new Expo project and added an expo-module. This command made the iOS and Android folders. I don't know if this matters.

iOS:
```
  240 | #endif
  241 | 
> 242 | #import <VisionCamera/VisionCamera.h>
      |         ^ 'VisionCamera/VisionCamera.h' file not found
  243 | 
  244 | #endif
  245 | #pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
```

Android:
When opening it in Android Studio and typing the import manually the auto completion does not see that there is a .camera in androidx.
```
> Task :app:compileDebugJavaWithJavac FAILED
/testexpots/xyzframeprocessor/XyzFrameProcessorPlugin.java:3: error: cannot find symbol
import androidx.camera.core.ImageProxy;
                           ^
  symbol:   class ImageProxy
  location: package androidx.camera.core
testexpots/xyzframeprocessor/XyzFrameProcessorPlugin.java:9: error: cannot find symbol
  public Object callback(ImageProxy image, Object[] params) {
                         ^
  symbol:   class ImageProxy
  location: class XyzFrameProcessorPlugin
texpots/MainApplication.java:36: error: cannot find symbol
        packages.add(new XyzFrameProcessorPluginPackage());
                         ^
  symbol: class XyzFrameProcessorPluginPackage
```

I also added the following to babel however my VSCode gives me an error for the __xyz method saying it does not exist.
```
[
  'react-native-reanimated/plugin',
  {
    globals: ['__xyz'],
  },
],
```

**Comment by kenhuang1964** [comment]
Hey @Egbert-Jan, does this work with expo?
