### ISSUE TITLE
Why the ML show only a few labels?

### ISSUE THREAD

**Issue by patras1** [mrousavy/vision-camera-image-labeler#22]
I have installed the labeler but it shows only a few labels no matter what the camera sees: Metal, curtain ,pattern, food.
Does anybody know how can I make it show labels for food item?
Let say banana, apple,egg etc... 

Thanks,
Dan

**Comment by mrousavy** [comment]
Hey I think this is due to the fact that the input format (RGB/YUV) or the orientation (landscape/portrait) is wrong.

I didn't update this repo in a while and I think the future should be the TensorFlow Lite package I'm drafting up for V3 launch.
