### ISSUE TITLE
IOS build fails due to conversion error.

### ISSUE THREAD

**Issue by Kypsis** [mrousavy/vision-camera-image-labeler#3]
<img width="1342" alt="Screenshot 2021-08-03 at 09 26 26" src="https://user-images.githubusercontent.com/46851868/127968245-ebc05448-7259-45de-a619-0d1ab5766ada.png">

Trying to build with Xcode 12.5.1 throws that error.

**Comment by mrousavy** [comment]
Fixed with https://github.com/mrousavy/vision-camera-image-labeler/commit/5fe5ac3c3eb3506e6bd2d580f4950b1b6ae70cb1
