### ISSUE TITLE
Module MLKit not found

### ISSUE THREAD

**Issue by Kypsis** [mrousavy/vision-camera-image-labeler#4]
In `VisionCameraImageLabeler.m` Xcode complains about `Module 'MLKit' not found` on line 13 `@import MLKit;`. If you delete that import the build fails at the very end with:
`duplicate symbol '_OBJC_CLASS_$_CameraViewManager' in:
    /Users/harrysild/Library/Developer/Xcode/DerivedData/Dashcam-cujsxchigczhdvbgfkjhdhokpctr/Build/Intermediates.noindex/Dashcam.build/StagingDebug-iphoneos/Dashcam.build/Objects-normal/arm64/CameraViewManager-e2616307afa5333b3b6da1885b39637cff4d06f18eed5d8b3bc0e505c1525a74.o
    /Users/harrysild/Library/Developer/Xcode/DerivedData/Dashcam-cujsxchigczhdvbgfkjhdhokpctr/Build/Products/StagingDebug-iphoneos/VisionCamera/libVisionCamera.a(CameraViewManager-6de0dcf57a6e5b176e919ac2555340718db92047184fdb2efecb0f346968c41a.o)
duplicate symbol '_OBJC_METACLASS_$_CameraViewManager' in:
    /Users/harrysild/Library/Developer/Xcode/DerivedData/Dashcam-cujsxchigczhdvbgfkjhdhokpctr/Build/Intermediates.noindex/Dashcam.build/StagingDebug-iphoneos/Dashcam.build/Objects-normal/arm64/CameraViewManager-e2616307afa5333b3b6da1885b39637cff4d06f18eed5d8b3bc0e505c1525a74.o
    /Users/harrysild/Library/Developer/Xcode/DerivedData/Dashcam-cujsxchigczhdvbgfkjhdhokpctr/Build/Products/StagingDebug-iphoneos/VisionCamera/libVisionCamera.a(CameraViewManager-6de0dcf57a6e5b176e919ac2555340718db92047184fdb2efecb0f346968c41a.o)
ld: 2 duplicate symbols for architecture arm64`

**Comment by mrousavy** [comment]
Fixed by https://github.com/mrousavy/vision-camera-image-labeler/commit/68a9a8301acc71b6805816af3476bc029f05accf
