### ISSUE TITLE
Update Fix MLKit import not found need to add to current version :)

### ISSUE THREAD

**Issue by NguyenPhatBG** [mrousavy/vision-camera-image-labeler#6]
https://github.com/mrousavy/vision-camera-image-labeler/commit/68a9a8301acc71b6805816af3476bc029f05accf
Good afternoon @mrousavy , I'm notice that the commit above not in current version when I install package (v0.1.5), Please update in new version, Thanks man!

**Comment by mrousavy** [comment]
done. 0.1.6 released
